#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from apl.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "apl.y"

#include<stdio.h>
#include<stdlib.h>
#include "apl.h"
extern FILE *yyin;

#line 7 "apl.y"
typedef union
{
	struct tree *n;
	struct ArgStruct *arg;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	NUM	258
#define	OPER1	259
#define	OPER2	260
#define	ID	261
#define	INT	262
#define	STR	263
#define	STRING	264
#define	MAIN	265
#define	BEGN	266
#define	END	267
#define	DECL	268
#define	ENDDECL	269
#define	ASG	270
#define	READ	271
#define	PRINT	272
#define	RELOP	273
#define	LOGOP	274
#define	NEGOP	275
#define	IF	276
#define	ELSE	277
#define	THEN	278
#define	ENDIF	279
#define	WHILE	280
#define	DO	281
#define	ENDWHILE	282
#define	RETURN	283
#define	SYSCREA	284
#define	SYSOPEN	285
#define	SYSWRIT	286
#define	SYSSEEK	287
#define	SYSREAD	288
#define	SYSCLOS	289
#define	SYSDELE	290
#define	SYSFORK	291
#define	SYSEXEC	292
#define	SYSEXIT	293
#define	SYSGPID	294
#define	SYSGPPID	295
#define	SYSWAIT	296
#define	SYSSIGNAL	297
#define	BREAK	298
#define	CONTINUE	299
#define	BREAKPOINT	300
#define	UMIN	301


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int NUM;
static const int OPER1;
static const int OPER2;
static const int ID;
static const int INT;
static const int STR;
static const int STRING;
static const int MAIN;
static const int BEGN;
static const int END;
static const int DECL;
static const int ENDDECL;
static const int ASG;
static const int READ;
static const int PRINT;
static const int RELOP;
static const int LOGOP;
static const int NEGOP;
static const int IF;
static const int ELSE;
static const int THEN;
static const int ENDIF;
static const int WHILE;
static const int DO;
static const int ENDWHILE;
static const int RETURN;
static const int SYSCREA;
static const int SYSOPEN;
static const int SYSWRIT;
static const int SYSSEEK;
static const int SYSREAD;
static const int SYSCLOS;
static const int SYSDELE;
static const int SYSFORK;
static const int SYSEXEC;
static const int SYSEXIT;
static const int SYSGPID;
static const int SYSGPPID;
static const int SYSWAIT;
static const int SYSSIGNAL;
static const int BREAK;
static const int CONTINUE;
static const int BREAKPOINT;
static const int UMIN;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,NUM=258
	,OPER1=259
	,OPER2=260
	,ID=261
	,INT=262
	,STR=263
	,STRING=264
	,MAIN=265
	,BEGN=266
	,END=267
	,DECL=268
	,ENDDECL=269
	,ASG=270
	,READ=271
	,PRINT=272
	,RELOP=273
	,LOGOP=274
	,NEGOP=275
	,IF=276
	,ELSE=277
	,THEN=278
	,ENDIF=279
	,WHILE=280
	,DO=281
	,ENDWHILE=282
	,RETURN=283
	,SYSCREA=284
	,SYSOPEN=285
	,SYSWRIT=286
	,SYSSEEK=287
	,SYSREAD=288
	,SYSCLOS=289
	,SYSDELE=290
	,SYSFORK=291
	,SYSEXEC=292
	,SYSEXIT=293
	,SYSGPID=294
	,SYSGPPID=295
	,SYSWAIT=296
	,SYSSIGNAL=297
	,BREAK=298
	,CONTINUE=299
	,BREAKPOINT=300
	,UMIN=301


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::NUM=258;
const int YY_parse_CLASS::OPER1=259;
const int YY_parse_CLASS::OPER2=260;
const int YY_parse_CLASS::ID=261;
const int YY_parse_CLASS::INT=262;
const int YY_parse_CLASS::STR=263;
const int YY_parse_CLASS::STRING=264;
const int YY_parse_CLASS::MAIN=265;
const int YY_parse_CLASS::BEGN=266;
const int YY_parse_CLASS::END=267;
const int YY_parse_CLASS::DECL=268;
const int YY_parse_CLASS::ENDDECL=269;
const int YY_parse_CLASS::ASG=270;
const int YY_parse_CLASS::READ=271;
const int YY_parse_CLASS::PRINT=272;
const int YY_parse_CLASS::RELOP=273;
const int YY_parse_CLASS::LOGOP=274;
const int YY_parse_CLASS::NEGOP=275;
const int YY_parse_CLASS::IF=276;
const int YY_parse_CLASS::ELSE=277;
const int YY_parse_CLASS::THEN=278;
const int YY_parse_CLASS::ENDIF=279;
const int YY_parse_CLASS::WHILE=280;
const int YY_parse_CLASS::DO=281;
const int YY_parse_CLASS::ENDWHILE=282;
const int YY_parse_CLASS::RETURN=283;
const int YY_parse_CLASS::SYSCREA=284;
const int YY_parse_CLASS::SYSOPEN=285;
const int YY_parse_CLASS::SYSWRIT=286;
const int YY_parse_CLASS::SYSSEEK=287;
const int YY_parse_CLASS::SYSREAD=288;
const int YY_parse_CLASS::SYSCLOS=289;
const int YY_parse_CLASS::SYSDELE=290;
const int YY_parse_CLASS::SYSFORK=291;
const int YY_parse_CLASS::SYSEXEC=292;
const int YY_parse_CLASS::SYSEXIT=293;
const int YY_parse_CLASS::SYSGPID=294;
const int YY_parse_CLASS::SYSGPPID=295;
const int YY_parse_CLASS::SYSWAIT=296;
const int YY_parse_CLASS::SYSSIGNAL=297;
const int YY_parse_CLASS::BREAK=298;
const int YY_parse_CLASS::CONTINUE=299;
const int YY_parse_CLASS::BREAKPOINT=300;
const int YY_parse_CLASS::UMIN=301;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		194
#define	YYFLAG		-32768
#define	YYNTBASE	56

#define YYTRANSLATE(x) ((unsigned)(x) <= 301 ? yytranslate[x] : 88)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    55,     2,    51,
    52,     2,     2,    48,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    47,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    49,     2,    50,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    53,     2,    54,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     4,     5,     9,    11,    14,    18,    20,    22,    24,
    28,    30,    35,    40,    41,    44,    53,    55,    57,    59,
    61,    62,    64,    68,    71,    73,    75,    77,    81,    83,
    86,    94,    96,   100,   102,   106,   108,   111,   113,   117,
   120,   122,   127,   133,   139,   146,   155,   162,   164,   169,
   172,   175,   178,   180,   182,   186,   190,   194,   198,   201,
   205,   208,   210,   212,   214,   216,   218,   223,   228,   229,
   231,   235,   240,   245,   250,   255,   260,   265,   270,   274,
   279,   283,   287,   292
};

static const short yyrhs[] = {    57,
    63,    73,     0,     0,    13,    58,    14,     0,    59,     0,
    58,    59,     0,    60,    61,    47,     0,     7,     0,     8,
     0,    62,     0,    61,    48,    62,     0,     6,     0,     6,
    49,     3,    50,     0,     6,    51,    68,    52,     0,     0,
    63,    64,     0,    65,    66,    51,    67,    52,    53,    78,
    54,     0,     7,     0,     8,     0,     6,     0,    68,     0,
     0,    69,     0,    68,    47,    69,     0,    70,    71,     0,
     7,     0,     8,     0,    72,     0,    71,    48,    72,     0,
     6,     0,    55,     6,     0,     7,    74,    51,    52,    53,
    78,    54,     0,    10,     0,    60,    76,    47,     0,    77,
     0,    76,    48,    77,     0,     6,     0,    80,    79,     0,
    79,     0,    28,    84,    47,     0,    80,    81,     0,    81,
     0,    85,    15,    84,    47,     0,    16,    51,    85,    52,
    47,     0,    17,    51,    84,    52,    47,     0,    82,    84,
    23,    80,    24,    47,     0,    82,    84,    23,    80,    22,
    80,    24,    47,     0,    83,    84,    26,    80,    27,    47,
     0,    75,     0,    38,    51,    52,    47,     0,    43,    47,
     0,    44,    47,     0,    45,    47,     0,    21,     0,    25,
     0,    84,     4,    84,     0,    84,     5,    84,     0,    84,
    18,    84,     0,    84,    19,    84,     0,    20,    84,     0,
    51,    84,    52,     0,     4,    84,     0,    87,     0,     3,
     0,     9,     0,    85,     0,     6,     0,     6,    49,    84,
    50,     0,     6,    51,    86,    52,     0,     0,    84,     0,
    86,    48,    84,     0,    29,    51,    86,    52,     0,    30,
    51,    86,    52,     0,    31,    51,    86,    52,     0,    32,
    51,    86,    52,     0,    33,    51,    86,    52,     0,    34,
    51,    86,    52,     0,    35,    51,    86,    52,     0,    36,
    51,    52,     0,    37,    51,    86,    52,     0,    39,    51,
    52,     0,    40,    51,    52,     0,    41,    51,    86,    52,
     0,    42,    51,    52,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    23,    26,    33,    41,    43,    46,    48,    50,    53,    55,
    58,    60,    62,    71,    73,    76,    87,    89,    93,   100,
   105,   107,   109,   113,   116,   118,   122,   124,   128,   131,
   135,   146,   158,   161,   163,   166,   170,   172,   175,   179,
   181,   185,   187,   189,   192,   194,   196,   198,   200,   202,
   209,   216,   220,   226,   233,   235,   237,   239,   241,   243,
   245,   247,   249,   251,   253,   257,   259,   261,   270,   272,
   274,   278,   280,   282,   284,   286,   288,   290,   292,   294,
   296,   298,   300,   302
};

static const char * const yytname[] = {   "$","error","$illegal.","NUM","OPER1",
"OPER2","ID","INT","STR","STRING","MAIN","BEGN","END","DECL","ENDDECL","ASG",
"READ","PRINT","RELOP","LOGOP","NEGOP","IF","ELSE","THEN","ENDIF","WHILE","DO",
"ENDWHILE","RETURN","SYSCREA","SYSOPEN","SYSWRIT","SYSSEEK","SYSREAD","SYSCLOS",
"SYSDELE","SYSFORK","SYSEXEC","SYSEXIT","SYSGPID","SYSGPPID","SYSWAIT","SYSSIGNAL",
"BREAK","CONTINUE","BREAKPOINT","UMIN","';'","','","'['","']'","'('","')'","'{'",
"'}'","'&'","prog","GDefblock","GDefList","GDecl","Type","GIdList","GId","FDefList",
"Fdef","RType","fID","fArgList","ArgList","ArgDecl","ArgType","ArgIdList","ArgId",
"Mainblock","fMAIN","LDecl","LIdList","LId","Body","retstmt","stmtlist","stmt",
"ifpad","whilepad","expr","ids","param","SysCall",""
};
#endif

static const short yyr1[] = {     0,
    56,    57,    57,    58,    58,    59,    60,    60,    61,    61,
    62,    62,    62,    63,    63,    64,    65,    65,    66,    67,
    68,    68,    68,    69,    70,    70,    71,    71,    72,    72,
    73,    74,    75,    76,    76,    77,    78,    78,    79,    80,
    80,    81,    81,    81,    81,    81,    81,    81,    81,    81,
    81,    81,    82,    83,    84,    84,    84,    84,    84,    84,
    84,    84,    84,    84,    84,    85,    85,    85,    86,    86,
    86,    87,    87,    87,    87,    87,    87,    87,    87,    87,
    87,    87,    87,    87
};

static const short yyr2[] = {     0,
     3,     0,     3,     1,     2,     3,     1,     1,     1,     3,
     1,     4,     4,     0,     2,     8,     1,     1,     1,     1,
     0,     1,     3,     2,     1,     1,     1,     3,     1,     2,
     7,     1,     3,     1,     3,     1,     2,     1,     3,     2,
     1,     4,     5,     5,     6,     8,     6,     1,     4,     2,
     2,     2,     1,     1,     3,     3,     3,     3,     2,     3,
     2,     1,     1,     1,     1,     1,     4,     4,     0,     1,
     3,     4,     4,     4,     4,     4,     4,     4,     3,     4,
     3,     3,     4,     3
};

static const short yydefact[] = {     2,
     0,    14,     7,     8,     0,     4,     0,     0,     3,     5,
    11,     0,     9,    17,    18,    15,     0,     1,     0,    21,
     6,     0,    32,     0,    19,     0,     0,    25,    26,     0,
    22,     0,    10,     0,    21,    12,     0,    13,    29,     0,
    24,    27,     0,     0,    20,    23,    30,     0,     0,     0,
    28,    66,     0,     0,    53,    54,     0,     0,     0,     0,
     0,     0,    48,     0,    38,     0,    41,     0,     0,     0,
     0,     0,    69,     0,     0,    63,     0,    64,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,    65,    62,     0,    50,    51,    52,
    36,     0,    34,    31,    37,    40,     0,     0,     0,     0,
     0,    70,     0,     0,     0,    61,    59,    69,    69,    69,
    69,    69,    69,    69,     0,    69,     0,     0,    69,     0,
     0,     0,     0,     0,     0,    39,     0,    33,     0,     0,
     0,     0,    16,    67,     0,    68,     0,     0,     0,     0,
     0,     0,     0,     0,     0,    79,     0,    81,    82,     0,
    84,    60,    55,    56,    57,    58,    49,    35,     0,     0,
    42,    71,    43,    44,    72,    73,    74,    75,    76,    77,
    78,    80,    83,     0,     0,     0,     0,    45,    47,     0,
    46,     0,     0,     0
};

static const short yydefgoto[] = {   192,
     2,     5,     6,    62,    12,    13,     8,    16,    17,    26,
    44,    30,    31,    32,    41,    42,    18,    24,    63,   102,
   103,    64,    65,    66,    67,    68,    69,   112,    95,   113,
    96
};

static const short yypact[] = {     2,
    -1,-32768,-32768,-32768,    28,-32768,    17,    75,-32768,-32768,
   -35,    42,-32768,    20,-32768,-32768,    32,-32768,    41,   103,
-32768,    17,-32768,    14,-32768,    24,     3,-32768,-32768,   -44,
-32768,    -4,-32768,    49,   103,-32768,   103,-32768,-32768,    74,
    61,-32768,    50,    76,    87,-32768,-32768,    -4,   141,    73,
-32768,   -12,    86,   109,-32768,-32768,    37,   110,    95,    98,
   112,   161,-32768,   111,-32768,   141,-32768,    37,    37,   153,
   141,    37,    37,   164,    37,-32768,    37,-32768,    37,   120,
   124,   125,   145,   146,   149,   150,   154,   157,   167,   168,
   170,   171,    37,    89,-32768,-32768,   140,-32768,-32768,-32768,
-32768,    70,-32768,-32768,-32768,-32768,   212,   176,    37,   158,
    45,   159,   -20,   177,     0,-32768,-32768,    37,    37,    37,
    37,    37,    37,    37,   181,    37,   191,   194,    37,   196,
    29,    37,    37,    37,    37,-32768,   187,-32768,   161,   207,
   207,    94,-32768,-32768,    37,-32768,   202,   206,     7,    10,
    48,    54,    71,    79,    91,-32768,    92,-32768,-32768,   102,
-32768,-32768,   249,-32768,   151,     8,-32768,-32768,   108,   166,
-32768,   159,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,   207,   208,   209,   182,-32768,-32768,   210,
-32768,   258,   259,-32768
};

static const short yypgoto[] = {-32768,
-32768,-32768,   255,    55,-32768,   239,-32768,-32768,-32768,-32768,
-32768,   227,   226,-32768,-32768,   216,-32768,-32768,-32768,-32768,
   126,   195,   201,  -130,   -65,-32768,-32768,   -48,   -49,   118,
-32768
};


#define	YYLAST		267


static const short yytable[] = {    70,
   106,    39,    37,   132,   133,     3,     4,    38,    94,   169,
   170,   132,   133,    19,     1,    20,    70,   134,   135,   107,
   108,    70,    11,   111,   114,   134,   115,   145,   116,    23,
   117,   146,   132,   133,     3,     4,    72,    25,    73,    76,
    77,     9,    52,    27,   131,    78,   134,   135,   132,   133,
    40,   148,    36,   187,   145,     7,    79,   145,   175,     7,
   142,   176,   134,   135,    34,    80,    81,    82,    83,    84,
    85,    86,    87,    88,    35,    89,    90,    91,    92,    47,
   162,    14,    15,   163,   164,   165,   166,    93,    21,    22,
    70,    70,   132,   133,   144,   145,   172,   132,   133,   177,
    43,   145,    49,   106,   106,   178,   134,   135,    48,    28,
    29,   134,   135,    52,     3,     4,   138,   139,   145,    70,
    70,   106,   179,    53,    54,    71,   145,    50,    55,   184,
   180,   185,    56,    37,    70,   136,    74,    70,   145,   145,
   171,    98,   181,   182,    99,    58,    52,     3,     4,   145,
    59,    60,    61,   183,   132,   133,    53,    54,   100,    75,
    97,    55,   132,   133,   104,    56,   101,   109,    57,    52,
   118,    52,     3,     4,   119,   120,   134,   135,    58,   132,
   133,    53,    54,    59,    60,    61,    55,    52,     3,     4,
    56,   137,   186,   134,   135,   121,   122,    53,    54,   123,
   124,   141,    55,    58,   125,   190,    56,   126,    59,    60,
    61,   143,    52,     3,     4,   132,   133,   127,   128,    58,
   129,   130,    53,    54,    59,    60,    61,    55,   147,   134,
   135,    56,   156,   167,   140,   149,   150,   151,   152,   153,
   154,   155,   158,   157,    58,   159,   160,   161,   173,    59,
    60,    61,   174,   133,   188,   189,   191,   193,   194,    10,
    33,    45,    46,    51,   168,   110,   105
};

static const short yycheck[] = {    49,
    66,     6,    47,     4,     5,     7,     8,    52,    57,   140,
   141,     4,     5,    49,    13,    51,    66,    18,    19,    68,
    69,    71,     6,    72,    74,    18,    75,    48,    77,    10,
    79,    52,     4,     5,     7,     8,    49,     6,    51,     3,
     4,    14,     6,     3,    93,     9,    18,    19,     4,     5,
    55,    52,    50,   184,    48,     1,    20,    48,    52,     5,
   109,    52,    18,    19,    51,    29,    30,    31,    32,    33,
    34,    35,    36,    37,    51,    39,    40,    41,    42,     6,
    52,     7,     8,   132,   133,   134,   135,    51,    47,    48,
   140,   141,     4,     5,    50,    48,   145,     4,     5,    52,
    52,    48,    53,   169,   170,    52,    18,    19,    48,     7,
     8,    18,    19,     6,     7,     8,    47,    48,    48,   169,
   170,   187,    52,    16,    17,    53,    48,    52,    21,    22,
    52,    24,    25,    47,   184,    47,    51,   187,    48,    48,
    47,    47,    52,    52,    47,    38,     6,     7,     8,    48,
    43,    44,    45,    52,     4,     5,    16,    17,    47,    51,
    51,    21,     4,     5,    54,    25,     6,    15,    28,     6,
    51,     6,     7,     8,    51,    51,    18,    19,    38,     4,
     5,    16,    17,    43,    44,    45,    21,     6,     7,     8,
    25,    52,    27,    18,    19,    51,    51,    16,    17,    51,
    51,    26,    21,    38,    51,    24,    25,    51,    43,    44,
    45,    54,     6,     7,     8,     4,     5,    51,    51,    38,
    51,    51,    16,    17,    43,    44,    45,    21,    52,    18,
    19,    25,    52,    47,    23,   118,   119,   120,   121,   122,
   123,   124,    52,   126,    38,    52,   129,    52,    47,    43,
    44,    45,    47,     5,    47,    47,    47,     0,     0,     5,
    22,    35,    37,    48,   139,    71,    66
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 23 "apl.y"
{;
    break;}
case 2:
#line 26 "apl.y"
{
							fflush(fp);
							main_pos = ftell(fp);
							out_linecount++;
							fprintf(fp,"JMP 00000\n");
							;
    break;}
case 3:
#line 33 "apl.y"
{
							fflush(fp);
							main_pos = ftell(fp);
							out_linecount++;
							fprintf(fp,"JMP 00000\n");
							;
    break;}
case 4:
#line 41 "apl.y"
{;
    break;}
case 5:
#line 43 "apl.y"
{;
    break;}
case 6:
#line 46 "apl.y"
{;
    break;}
case 7:
#line 48 "apl.y"
{m=0;
							;
    break;}
case 8:
#line 50 "apl.y"
{m=3;
							;
    break;}
case 9:
#line 53 "apl.y"
{;
    break;}
case 10:
#line 55 "apl.y"
{;
    break;}
case 11:
#line 58 "apl.y"
{install(yyvsp[0].n,m,1);
							;
    break;}
case 12:
#line 60 "apl.y"
{install(yyvsp[-3].n,m,yyvsp[-1].n->value);
							;
    break;}
case 13:
#line 62 "apl.y"
{finstall(yyvsp[-3].n,m,yyvsp[-1].arg);
							/*while($3!=NULL)
							{
								printf(" %s-%d\n",$3->name,$3->type);
								$3=$3->next;
							}*/
							;
    break;}
case 14:
#line 71 "apl.y"
{;
    break;}
case 15:
#line 73 "apl.y"
{;
    break;}
case 16:
#line 76 "apl.y"
{/*struct Lsymbol *temp=Lroot;
									while(temp!=NULL)
									{
										printf(" %s-%d-%d\n",temp->name,temp->type,temp->bind);
										temp=temp->next;
									}*/
									codegen(yyvsp[-1].n);
									Lroot=NULL;
									funcid=NULL;										
									;
    break;}
case 17:
#line 87 "apl.y"
{m3=0;
							;
    break;}
case 18:
#line 89 "apl.y"
{m3=3;
							;
    break;}
case 19:
#line 93 "apl.y"
{memcount=1;
							yyvsp[0].n->type=m3;
							funcid=yyvsp[0].n;
							yyval.n=yyvsp[0].n;
							;
    break;}
case 20:
#line 100 "apl.y"
{fdefcheck(funcid,yyvsp[0].arg,m3);
							arglistinstall(funcid);
							;
    break;}
case 21:
#line 105 "apl.y"
{yyval.arg=NULL;
							;
    break;}
case 22:
#line 107 "apl.y"
{yyval.arg=yyvsp[0].arg;							
							;
    break;}
case 23:
#line 109 "apl.y"
{yyval.arg=makeargtree(yyvsp[-2].arg,yyvsp[0].arg);							
							;
    break;}
case 24:
#line 113 "apl.y"
{yyval.arg=yyvsp[0].arg;;
    break;}
case 25:
#line 116 "apl.y"
{m2=0;
							;
    break;}
case 26:
#line 118 "apl.y"
{m2=3;
							;
    break;}
case 27:
#line 122 "apl.y"
{yyval.arg=yyvsp[0].arg;
							;
    break;}
case 28:
#line 124 "apl.y"
{yyval.arg=makeargtree(yyvsp[-2].arg,yyvsp[0].arg);
							;
    break;}
case 29:
#line 128 "apl.y"
{
							yyval.arg=makearg(yyvsp[0].n->name,m2,0);
							;
    break;}
case 30:
#line 131 "apl.y"
{yyval.arg=makearg(yyvsp[0].n->name,m2,1);
							;
    break;}
case 31:
#line 135 "apl.y"
{codegen(yyvsp[-1].n);
							out_linecount+=2;
							fprintf(fp, "MOV R0, 10\nPUSH R0\n");
							out_linecount++;
							fprintf(fp, "INT 7\n");;
							fclose(fp);						
				 			//printf("%d Lines Compiled\n",linecount);
							return(0);
							;
    break;}
case 32:
#line 146 "apl.y"
{m3=0;
							memcount=1;
							funcid=NULL;
							fflush(fp);
							temp_pos = ftell(fp);
							fseek(fp,main_pos,SEEK_SET);
							fprintf(fp,"JMP %05d",out_linecount*2);
							fseek(fp,temp_pos,SEEK_SET);
							out_linecount+=2; fprintf(fp,"PUSH BP\nMOV BP,SP\n"); 
							;
    break;}
case 33:
#line 158 "apl.y"
{;
    break;}
case 34:
#line 161 "apl.y"
{;
    break;}
case 35:
#line 163 "apl.y"
{;
    break;}
case 36:
#line 166 "apl.y"
{Linstall(yyvsp[0].n,m,1);
							;
    break;}
case 37:
#line 170 "apl.y"
{yyval.n=nontermcreate("Body",yyvsp[-1].n,yyvsp[0].n);			
							;
    break;}
case 38:
#line 172 "apl.y"
{yyval.n=nontermcreate("Body",yyvsp[0].n,NULL);			
							;
    break;}
case 39:
#line 175 "apl.y"
{yyval.n=maketree(yyvsp[-2].n,yyvsp[-1].n,NULL,NULL);
							;
    break;}
case 40:
#line 179 "apl.y"
{yyval.n=nontermcreate("stmtlist",yyvsp[-1].n,yyvsp[0].n);
							;
    break;}
case 41:
#line 181 "apl.y"
{yyval.n=yyvsp[0].n;
							;
    break;}
case 42:
#line 185 "apl.y"
{yyval.n=maketree(yyvsp[-2].n,yyvsp[-3].n,yyvsp[-1].n,NULL);
							;
    break;}
case 43:
#line 187 "apl.y"
{yyval.n=maketree(yyvsp[-4].n,yyvsp[-2].n,NULL,NULL);
							;
    break;}
case 44:
#line 189 "apl.y"
{yyval.n=maketree(yyvsp[-4].n,yyvsp[-2].n,NULL,NULL);
							;
    break;}
case 45:
#line 192 "apl.y"
{yyval.n=maketree(yyvsp[-5].n,yyvsp[-4].n,yyvsp[-2].n,NULL);flag_decl--;
										;
    break;}
case 46:
#line 194 "apl.y"
{yyval.n=maketree(yyvsp[-7].n,yyvsp[-6].n,yyvsp[-4].n,yyvsp[-2].n);flag_decl--;
										;
    break;}
case 47:
#line 196 "apl.y"
{yyval.n=maketree(yyvsp[-5].n,yyvsp[-4].n,yyvsp[-2].n,NULL);flag_decl--;flag_break=0;
										;
    break;}
case 48:
#line 198 "apl.y"
{yyval.n=NULL;
							;
    break;}
case 49:
#line 200 "apl.y"
{yyval.n=yyvsp[-3].n;		
							;
    break;}
case 50:
#line 202 "apl.y"
{if(flag_break==0)
							{
								printf("\n%d: break or continue should be used inside while!!\n",linecount);
								exit(0);								
							}
							yyval.n=yyvsp[-1].n;
							;
    break;}
case 51:
#line 209 "apl.y"
{if(flag_break==0)
							{
								printf("\n%d: break or continue should be used inside while!!\n",linecount);
								exit(0);								
							}
							yyval.n=yyvsp[-1].n;
							;
    break;}
case 52:
#line 216 "apl.y"
{yyval.n=yyvsp[-1].n;		
							;
    break;}
case 53:
#line 220 "apl.y"
{
								flag_decl++;
								yyval.n=yyvsp[0].n;
							;
    break;}
case 54:
#line 226 "apl.y"
{
								flag_decl++;
								flag_break=1;
								yyval.n=yyvsp[0].n;
							;
    break;}
case 55:
#line 233 "apl.y"
{yyval.n=maketree(yyvsp[-1].n,yyvsp[-2].n,yyvsp[0].n,NULL);
							;
    break;}
case 56:
#line 235 "apl.y"
{yyval.n=maketree(yyvsp[-1].n,yyvsp[-2].n,yyvsp[0].n,NULL);
							;
    break;}
case 57:
#line 237 "apl.y"
{yyval.n=maketree(yyvsp[-1].n,yyvsp[-2].n,yyvsp[0].n,NULL);
							;
    break;}
case 58:
#line 239 "apl.y"
{yyval.n=maketree(yyvsp[-1].n,yyvsp[-2].n,yyvsp[0].n,NULL);
							;
    break;}
case 59:
#line 241 "apl.y"
{yyval.n=maketree(yyvsp[-1].n,yyvsp[0].n,NULL,NULL);
							;
    break;}
case 60:
#line 243 "apl.y"
{yyval.n=yyvsp[-1].n;
							;
    break;}
case 61:
#line 245 "apl.y"
{yyval.n=maketree(yyvsp[-1].n,yyvsp[0].n,NULL,NULL);
							;
    break;}
case 62:
#line 247 "apl.y"
{yyval.n=yyvsp[0].n;
							;
    break;}
case 63:
#line 249 "apl.y"
{yyval.n=yyvsp[0].n;
							;
    break;}
case 64:
#line 251 "apl.y"
{yyval.n=yyvsp[0].n;
							;
    break;}
case 65:
#line 253 "apl.y"
{yyval.n=yyvsp[0].n;
							;
    break;}
case 66:
#line 257 "apl.y"
{yyval.n=maketree(yyvsp[0].n,NULL,NULL,NULL);
							;
    break;}
case 67:
#line 259 "apl.y"
{yyval.n=maketree(yyvsp[-3].n,yyvsp[-1].n,NULL,NULL);
							;
    break;}
case 68:
#line 261 "apl.y"
{yyval.n=functioncall(yyvsp[-3].n,yyvsp[-1].n);
							/*while($3!=NULL)
							{
								printf(" %s - %d\n",$3->name,$3->type);
								$3=$3->ptr3;
							}*/
							;
    break;}
case 69:
#line 270 "apl.y"
{yyval.n=NULL;
							;
    break;}
case 70:
#line 272 "apl.y"
{yyval.n=yyvsp[0].n;
							;
    break;}
case 71:
#line 274 "apl.y"
{yyval.n=makeparam(yyvsp[-2].n,yyvsp[0].n);
							;
    break;}
case 72:
#line 278 "apl.y"
{yyval.n=syscheck(yyvsp[-3].n,yyvsp[-1].n,1);
							;
    break;}
case 73:
#line 280 "apl.y"
{yyval.n=syscheck(yyvsp[-3].n,yyvsp[-1].n,1);
							;
    break;}
case 74:
#line 282 "apl.y"
{yyval.n=syscheck(yyvsp[-3].n,yyvsp[-1].n,5);
							;
    break;}
case 75:
#line 284 "apl.y"
{yyval.n=syscheck(yyvsp[-3].n,yyvsp[-1].n,3);
							;
    break;}
case 76:
#line 286 "apl.y"
{yyval.n=syscheck(yyvsp[-3].n,yyvsp[-1].n,2);
							;
    break;}
case 77:
#line 288 "apl.y"
{yyval.n=syscheck(yyvsp[-3].n,yyvsp[-1].n,4);
							;
    break;}
case 78:
#line 290 "apl.y"
{yyval.n=syscheck(yyvsp[-3].n,yyvsp[-1].n,1);
							;
    break;}
case 79:
#line 292 "apl.y"
{yyval.n=yyvsp[-2].n;
							;
    break;}
case 80:
#line 294 "apl.y"
{yyval.n=syscheck(yyvsp[-3].n,yyvsp[-1].n,1);
							;
    break;}
case 81:
#line 296 "apl.y"
{yyval.n=yyvsp[-2].n;
							;
    break;}
case 82:
#line 298 "apl.y"
{yyval.n=yyvsp[-2].n;
							;
    break;}
case 83:
#line 300 "apl.y"
{yyval.n=syscheck(yyvsp[-3].n,yyvsp[-1].n,4);
							;
    break;}
case 84:
#line 302 "apl.y"
{yyval.n=yyvsp[-2].n;
							;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 306 "apl.y"

int main (int argc, char **argv)
{	
	FILE *input_fp;
	char filename[200],ch;
	strcpy(filename,argv[1]);	
	if(argc < 2)
	{
		printf("Specify an input filename\n");
		return 0;
	}
	expandpath(filename);
	input_fp = fopen(filename,"r");
	if(!input_fp)
	{
		printf("Invalid input file\n");
		return 0;
	}
	yyin = input_fp;
	changeext(filename);
	fp=fopen(".temp","wb");
	out_linecount++; fprintf(fp,"START\n");
	out_linecount++; fprintf(fp,"MOV SP, 1535\n");
	out_linecount++; fprintf(fp,"MOV BP, 1535\n");
	yyparse();
	fclose(input_fp);
	input_fp = fopen(".temp","r");
	if(!input_fp)
	{
		printf("Writing compiled code to file failed\n");
		return 0;
	}
	fp = fopen(filename,"wb");
	if(!fp)
	{
		fclose(input_fp);
		printf("Writing compiled code to file failed\n");
		return 0;
	}
	while( ( ch = fgetc(input_fp) ) != EOF )
		fputc(ch, fp);
	fclose(input_fp);
	fclose(fp);	
	return 0;	
}
int yyerror (char *msg) 
{
	return fprintf (stderr, "%d: %s\n",linecount,msg);
}
