#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from spl.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "spl.y"

#include<stdio.h>
#include<stdlib.h>
#include "spl.h"
extern FILE *yyin;

#line 7 "spl.y"
typedef union
{
	struct tree *n;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	ALIAS	258
#define	DEFINE	259
#define	DO	260
#define	ELSE	261
#define	ENDIF	262
#define	ENDWHILE	263
#define	IF	264
#define	IRETURN	265
#define	LOAD	266
#define	STORE	267
#define	THEN	268
#define	WHILE	269
#define	HALT	270
#define	REG	271
#define	NUM	272
#define	ASSIGNOP	273
#define	ARITHOP1	274
#define	ARITHOP2	275
#define	RELOP	276
#define	LOGOP	277
#define	NOTOP	278
#define	ID	279
#define	BREAK	280
#define	CONTINUE	281
#define	CHKPT	282
#define	READ	283
#define	PRINT	284
#define	STRING	285
#define	INLINE	286
#define	UMIN	287


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int ALIAS;
static const int DEFINE;
static const int DO;
static const int ELSE;
static const int ENDIF;
static const int ENDWHILE;
static const int IF;
static const int IRETURN;
static const int LOAD;
static const int STORE;
static const int THEN;
static const int WHILE;
static const int HALT;
static const int REG;
static const int NUM;
static const int ASSIGNOP;
static const int ARITHOP1;
static const int ARITHOP2;
static const int RELOP;
static const int LOGOP;
static const int NOTOP;
static const int ID;
static const int BREAK;
static const int CONTINUE;
static const int CHKPT;
static const int READ;
static const int PRINT;
static const int STRING;
static const int INLINE;
static const int UMIN;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,ALIAS=258
	,DEFINE=259
	,DO=260
	,ELSE=261
	,ENDIF=262
	,ENDWHILE=263
	,IF=264
	,IRETURN=265
	,LOAD=266
	,STORE=267
	,THEN=268
	,WHILE=269
	,HALT=270
	,REG=271
	,NUM=272
	,ASSIGNOP=273
	,ARITHOP1=274
	,ARITHOP2=275
	,RELOP=276
	,LOGOP=277
	,NOTOP=278
	,ID=279
	,BREAK=280
	,CONTINUE=281
	,CHKPT=282
	,READ=283
	,PRINT=284
	,STRING=285
	,INLINE=286
	,UMIN=287


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::ALIAS=258;
const int YY_parse_CLASS::DEFINE=259;
const int YY_parse_CLASS::DO=260;
const int YY_parse_CLASS::ELSE=261;
const int YY_parse_CLASS::ENDIF=262;
const int YY_parse_CLASS::ENDWHILE=263;
const int YY_parse_CLASS::IF=264;
const int YY_parse_CLASS::IRETURN=265;
const int YY_parse_CLASS::LOAD=266;
const int YY_parse_CLASS::STORE=267;
const int YY_parse_CLASS::THEN=268;
const int YY_parse_CLASS::WHILE=269;
const int YY_parse_CLASS::HALT=270;
const int YY_parse_CLASS::REG=271;
const int YY_parse_CLASS::NUM=272;
const int YY_parse_CLASS::ASSIGNOP=273;
const int YY_parse_CLASS::ARITHOP1=274;
const int YY_parse_CLASS::ARITHOP2=275;
const int YY_parse_CLASS::RELOP=276;
const int YY_parse_CLASS::LOGOP=277;
const int YY_parse_CLASS::NOTOP=278;
const int YY_parse_CLASS::ID=279;
const int YY_parse_CLASS::BREAK=280;
const int YY_parse_CLASS::CONTINUE=281;
const int YY_parse_CLASS::CHKPT=282;
const int YY_parse_CLASS::READ=283;
const int YY_parse_CLASS::PRINT=284;
const int YY_parse_CLASS::STRING=285;
const int YY_parse_CLASS::INLINE=286;
const int YY_parse_CLASS::UMIN=287;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		99
#define	YYFLAG		-32768
#define	YYNTBASE	39

#define YYTRANSLATE(x) ((unsigned)(x) <= 287 ? yytranslate[x] : 50)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    34,
    36,     2,     2,    35,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    33,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    37,     2,    38,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     5,     6,     9,    14,    20,    23,    25,    30,
    37,    46,    53,    58,    66,    74,    77,    80,    83,    86,
    90,    93,    97,   101,   105,   109,   113,   117,   120,   123,
   127,   131,   133,   135,   137,   139,   141,   143,   145
};

static const short yyrhs[] = {    40,
    43,     0,    41,     0,     0,    41,    42,     0,     4,    24,
    17,    33,     0,     4,    24,    19,    17,    33,     0,    43,
    44,     0,    44,     0,    45,    18,    45,    33,     0,    46,
    45,    13,    43,     7,    33,     0,    46,    45,    13,    43,
    47,    43,     7,    33,     0,    48,    45,     5,    43,     8,
    33,     0,     3,    24,    16,    33,     0,    11,    34,    45,
    35,    45,    36,    33,     0,    12,    34,    45,    35,    45,
    36,    33,     0,    10,    33,     0,    25,    33,     0,    26,
    33,     0,    15,    33,     0,    31,    30,    33,     0,    27,
    33,     0,    28,    49,    33,     0,    29,    45,    33,     0,
    45,    19,    45,     0,    45,    20,    45,     0,    45,    21,
    45,     0,    45,    22,    45,     0,    19,    17,     0,    23,
    45,     0,    37,    45,    38,     0,    34,    45,    36,     0,
    17,     0,    49,     0,    30,     0,     9,     0,     6,     0,
    14,     0,    24,     0,    16,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    20,    27,    31,    33,    37,    40,    48,    51,    56,    68,
    73,    79,    85,    89,    92,    95,    98,   105,   112,   115,
   121,   124,   132,   138,   141,   144,   147,   150,   155,   158,
   162,   165,   168,   171,   176,   181,   186,   193,   196
};

static const char * const yytname[] = {   "$","error","$illegal.","ALIAS","DEFINE",
"DO","ELSE","ENDIF","ENDWHILE","IF","IRETURN","LOAD","STORE","THEN","WHILE",
"HALT","REG","NUM","ASSIGNOP","ARITHOP1","ARITHOP2","RELOP","LOGOP","NOTOP",
"ID","BREAK","CONTINUE","CHKPT","READ","PRINT","STRING","INLINE","UMIN","';'",
"'('","','","')'","'['","']'","body","definelistpad","definelist","definestmt",
"stmtlist","stmt","expr","ifpad","elsepad","whilepad","ids",""
};
#endif

static const short yyr1[] = {     0,
    39,    40,    41,    41,    42,    42,    43,    43,    44,    44,
    44,    44,    44,    44,    44,    44,    44,    44,    44,    44,
    44,    44,    44,    45,    45,    45,    45,    45,    45,    45,
    45,    45,    45,    45,    46,    47,    48,    49,    49
};

static const short yyr2[] = {     0,
     2,     1,     0,     2,     4,     5,     2,     1,     4,     6,
     8,     6,     4,     7,     7,     2,     2,     2,     2,     3,
     2,     3,     3,     3,     3,     3,     3,     2,     2,     3,
     3,     1,     1,     1,     1,     1,     1,     1,     1
};

static const short yydefact[] = {     3,
     0,     2,     0,    35,     0,     0,     0,    37,     0,    39,
    32,     0,     0,    38,     0,     0,     0,     0,     0,    34,
     0,     0,     0,     1,     8,     0,     0,     0,    33,     0,
     4,     0,    16,     0,     0,    19,    28,    29,    17,    18,
    21,     0,     0,     0,     0,     0,     7,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,    22,    23,
    20,    31,    30,     0,    24,    25,    26,    27,     0,     0,
     0,     0,    13,     0,     0,     9,     0,     0,     5,     0,
     0,     0,    36,     0,     0,     0,     6,     0,     0,    10,
     0,    12,    14,    15,     0,    11,     0,     0,     0
};

static const short yydefgoto[] = {    97,
     1,     2,    31,    24,    25,    26,    27,    85,    28,    29
};

static const short yypact[] = {-32768,
   150,    21,     2,-32768,    -1,     9,    10,-32768,    13,-32768,
-32768,    38,    11,-32768,    14,    27,    28,   -10,    11,-32768,
    34,    11,    11,   150,-32768,   205,    11,    11,-32768,    46,
-32768,    59,-32768,    11,    11,-32768,-32768,-32768,-32768,-32768,
-32768,    47,   181,    61,    30,   -17,-32768,    11,    11,    11,
    11,    11,   200,    37,    12,    64,    -2,   177,-32768,-32768,
-32768,-32768,-32768,   196,    78,-32768,    -7,    63,   150,   150,
    72,    93,-32768,    11,    11,-32768,    62,    92,-32768,    79,
   169,   173,-32768,    80,   150,    81,-32768,    94,   101,-32768,
   121,-32768,-32768,-32768,   106,-32768,   125,   141,-32768
};

static const short yypgoto[] = {-32768,
-32768,-32768,-32768,   -61,   -24,   -12,-32768,-32768,-32768,   124
};


#define	YYLAST		229


static const short yytable[] = {    47,
    38,    49,    50,    51,    52,    10,    43,    77,    78,    45,
    46,    49,    50,    14,    53,    54,    49,    50,    51,    52,
    63,    57,    58,    91,    30,    32,    10,    11,    71,    12,
    72,    33,    74,    13,    14,    64,    65,    66,    67,    68,
    20,    70,    34,    35,    22,    36,    39,    23,    49,    50,
    51,    52,    47,    47,    37,    49,    50,    51,    52,    40,
    41,    81,    82,    44,     3,    62,    47,    83,    84,    55,
     4,     5,     6,     7,    56,     8,     9,    10,    11,    59,
    12,    49,    50,    51,    13,    14,    15,    16,    17,    18,
    19,    20,    21,    61,     3,    22,    73,    50,    23,    86,
     4,     5,     6,     7,    79,     8,     9,    10,    11,    80,
    12,    87,    90,    92,    13,    14,    15,    16,    17,    18,
    19,    20,    21,     3,    98,    22,    93,    95,    23,     4,
     5,     6,     7,    94,     8,     9,    10,    11,    96,    12,
    99,    42,     0,    13,    14,    15,    16,    17,    18,    19,
    20,    21,     3,     0,    22,     0,     0,    23,     4,     5,
     6,     7,     0,     8,     9,    10,    11,     0,    12,     0,
     0,     0,    13,    14,    15,    16,    17,    18,    19,    20,
    21,     0,     0,    22,     0,     0,    23,    49,    50,    51,
    52,    49,    50,    51,    52,    49,    50,    51,    52,    49,
    50,    51,    52,     0,    88,     0,     0,     0,    89,     0,
     0,    75,    69,    60,    49,    50,    51,    52,    49,    50,
    51,    52,    48,    49,    50,    51,    52,     0,    76
};

static const short yycheck[] = {    24,
    13,    19,    20,    21,    22,    16,    19,    69,    70,    22,
    23,    19,    20,    24,    27,    28,    19,    20,    21,    22,
    38,    34,    35,    85,     4,    24,    16,    17,    17,    19,
    19,    33,    35,    23,    24,    48,    49,    50,    51,    52,
    30,     5,    34,    34,    34,    33,    33,    37,    19,    20,
    21,    22,    77,    78,    17,    19,    20,    21,    22,    33,
    33,    74,    75,    30,     3,    36,    91,     6,     7,    24,
     9,    10,    11,    12,    16,    14,    15,    16,    17,    33,
    19,    19,    20,    21,    23,    24,    25,    26,    27,    28,
    29,    30,    31,    33,     3,    34,    33,    20,    37,     8,
     9,    10,    11,    12,    33,    14,    15,    16,    17,    17,
    19,    33,    33,    33,    23,    24,    25,    26,    27,    28,
    29,    30,    31,     3,     0,    34,    33,     7,    37,     9,
    10,    11,    12,    33,    14,    15,    16,    17,    33,    19,
     0,    18,    -1,    23,    24,    25,    26,    27,    28,    29,
    30,    31,     3,    -1,    34,    -1,    -1,    37,     9,    10,
    11,    12,    -1,    14,    15,    16,    17,    -1,    19,    -1,
    -1,    -1,    23,    24,    25,    26,    27,    28,    29,    30,
    31,    -1,    -1,    34,    -1,    -1,    37,    19,    20,    21,
    22,    19,    20,    21,    22,    19,    20,    21,    22,    19,
    20,    21,    22,    -1,    36,    -1,    -1,    -1,    36,    -1,
    -1,    35,    13,    33,    19,    20,    21,    22,    19,    20,
    21,    22,    18,    19,    20,    21,    22,    -1,    33
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 20 "spl.y"
{
								codegen(yyvsp[0].n);
								out_linecount++;
								fprintf(fp,"HALT");
							;
    break;}
case 2:
#line 27 "spl.y"
{
								add_predefined_constants();
							;
    break;}
case 3:
#line 31 "spl.y"
{
							;
    break;}
case 4:
#line 33 "spl.y"
{
							;
    break;}
case 5:
#line 37 "spl.y"
{
								insert_constant(yyvsp[-2].n->name,yyvsp[-1].n->value);
							;
    break;}
case 6:
#line 40 "spl.y"
{
								if(yyvsp[-2].n->nodetype=='-')
									insert_constant(yyvsp[-3].n->name,-1*yyvsp[-1].n->value);
								else
									insert_constant(yyvsp[-3].n->name,yyvsp[-1].n->value);
							;
    break;}
case 7:
#line 48 "spl.y"
{
								yyval.n=create_nonterm_node("Body",yyvsp[-1].n,yyvsp[0].n);
							;
    break;}
case 8:
#line 51 "spl.y"
{
								yyval.n=yyvsp[0].n;
							;
    break;}
case 9:
#line 56 "spl.y"
{
								if(yyvsp[-3].n->nodetype=='R' || yyvsp[-3].n->nodetype=='m')
								{
									yyvsp[-2].n->value=2;
									yyval.n=create_tree(yyvsp[-2].n,yyvsp[-3].n,yyvsp[-1].n,NULL);
								}
								else
								{
									printf("\n%d:Invalid operands in assignment!!\n",linecount);
									exit(0);
								}
							;
    break;}
case 10:
#line 68 "spl.y"
{								
								yyval.n=create_tree(yyvsp[-5].n,yyvsp[-4].n,yyvsp[-2].n,NULL);
								pop_alias();
								depth--;
							;
    break;}
case 11:
#line 74 "spl.y"
{	
								yyval.n=create_tree(yyvsp[-7].n,yyvsp[-6].n,yyvsp[-4].n,yyvsp[-2].n);
								pop_alias();
								depth--;
							;
    break;}
case 12:
#line 79 "spl.y"
{
								yyval.n=create_tree(yyvsp[-5].n,yyvsp[-4].n,yyvsp[-2].n,NULL);
								pop_alias();
								depth--;
								flag_break--;
							;
    break;}
case 13:
#line 85 "spl.y"
{	
								push_alias(yyvsp[-2].n->name,yyvsp[-1].n->value);
								yyval.n=NULL;
							;
    break;}
case 14:
#line 89 "spl.y"
{
								yyval.n=create_tree(yyvsp[-6].n,yyvsp[-4].n,yyvsp[-2].n,NULL);
							;
    break;}
case 15:
#line 92 "spl.y"
{
								yyval.n=create_tree(yyvsp[-6].n,yyvsp[-4].n,yyvsp[-2].n,NULL);
							;
    break;}
case 16:
#line 95 "spl.y"
{
								yyval.n=yyvsp[-1].n;
							;
    break;}
case 17:
#line 98 "spl.y"
{if(flag_break==0)
							{
								printf("\n%d: break or continue should be used inside while!!\n",linecount);
								exit(0);								
							}
							yyval.n=yyvsp[-1].n;
							;
    break;}
case 18:
#line 105 "spl.y"
{if(flag_break==0)
							{
								printf("\n%d: break or continue should be used inside while!!\n",linecount);
								exit(0);								
							}
							yyval.n=yyvsp[-1].n;
							;
    break;}
case 19:
#line 112 "spl.y"
{	
							yyval.n=yyvsp[-1].n;
							;
    break;}
case 20:
#line 115 "spl.y"
{
							yyvsp[-1].n->name++;
							int temp=strlen(yyvsp[-1].n->name);
							yyvsp[-1].n->name[temp-1]='\0';
							yyval.n=create_tree(yyvsp[-2].n,yyvsp[-1].n,NULL,NULL);
							;
    break;}
case 21:
#line 121 "spl.y"
{	
							yyval.n=yyvsp[-1].n;
							;
    break;}
case 22:
#line 124 "spl.y"
{	
								if(yyvsp[-1].n->nodetype!='R')
								{
									printf("\n%d:Invalid operand in read!!\n",linecount);
									exit(0);
								}							
								yyval.n=create_tree(yyvsp[-2].n,yyvsp[-1].n,NULL,NULL);
							;
    break;}
case 23:
#line 132 "spl.y"
{
								yyval.n=create_tree(yyvsp[-2].n,yyvsp[-1].n,NULL,NULL);
							;
    break;}
case 24:
#line 138 "spl.y"
{
								yyval.n=create_tree(yyvsp[-1].n,yyvsp[-2].n,yyvsp[0].n,NULL);
							;
    break;}
case 25:
#line 141 "spl.y"
{
								yyval.n=create_tree(yyvsp[-1].n,yyvsp[-2].n,yyvsp[0].n,NULL);
							;
    break;}
case 26:
#line 144 "spl.y"
{
								yyval.n=create_tree(yyvsp[-1].n,yyvsp[-2].n,yyvsp[0].n,NULL);
							;
    break;}
case 27:
#line 147 "spl.y"
{
								yyval.n=create_tree(yyvsp[-1].n,yyvsp[-2].n,yyvsp[0].n,NULL);
							;
    break;}
case 28:
#line 150 "spl.y"
{
								if(yyvsp[-1].n->nodetype=='-')
									yyvsp[0].n->value=yyvsp[0].n->value*-1;
								yyval.n=yyvsp[0].n;
							;
    break;}
case 29:
#line 155 "spl.y"
{
								yyval.n=create_tree(yyvsp[-1].n,yyvsp[0].n,NULL,NULL);
							;
    break;}
case 30:
#line 158 "spl.y"
{
								yyval.n=create_nonterm_node("addr",yyvsp[-1].n,NULL);
								yyval.n->nodetype='m';
							;
    break;}
case 31:
#line 162 "spl.y"
{
								yyval.n=yyvsp[-1].n;
							;
    break;}
case 32:
#line 165 "spl.y"
{	
								yyval.n=yyvsp[0].n;
							;
    break;}
case 33:
#line 168 "spl.y"
{
								yyval.n=yyvsp[0].n;
							;
    break;}
case 34:
#line 171 "spl.y"
{
								yyval.n=yyvsp[0].n;
							;
    break;}
case 35:
#line 176 "spl.y"
{
								depth++;
								yyval.n=yyvsp[0].n;
							;
    break;}
case 36:
#line 181 "spl.y"
{
								pop_alias();
							;
    break;}
case 37:
#line 186 "spl.y"
{
								depth++;
								flag_break++;
								yyval.n=yyvsp[0].n;
							;
    break;}
case 38:
#line 193 "spl.y"
{							
								yyval.n=substitute_id(yyvsp[0].n);
							;
    break;}
case 39:
#line 196 "spl.y"
{
								yyval.n=yyvsp[0].n;
							;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 200 "spl.y"

int main (int argc,char **argv)
{	
	FILE *input_fp;
	char filename[200],ch;
	char op_name[200];
	if(argc < 3)
	{
		printf("Incorrect Usage.\nSee usage manual\n");
		exit(0);
	}
	strcpy(filename,argv[2]);
	expandpath(filename);
	input_fp = fopen(filename,"r");
	if(!input_fp)
	{
		printf("Invalid input file\n");
		return 0;
	}
	yyin = input_fp;
	remfilename(filename);
	strcpy( op_name, filename );
	if(strcmp(argv[1],"--os") == 0)
	{
		strcat(op_name,"os_startup.xsm");
		addrBaseVal = SCRATCHPAD;
	}
	else if(strcmp(argv[1],"--exhandler") == 0)
	{
		strcat(op_name,"exhandler.xsm");
		addrBaseVal = EX_HANDLER;
	}
	else if(strcmp(argv[1],"--int=timer") == 0)
	{
		strcat(op_name,"timer.xsm");
		addrBaseVal = T_INTERRUPT;
	}
	else if(strcmp(argv[1],"--int=1") == 0)
	{
		strcat(op_name,"int1.xsm");
		addrBaseVal = T_INTERRUPT + 1*PAGE_PER_INTERRUPT*PAGE_SIZE;
	}
	else if(strcmp(argv[1],"--int=2") == 0)
	{
		strcat(op_name,"int2.xsm");
		addrBaseVal = T_INTERRUPT + 2*PAGE_PER_INTERRUPT*PAGE_SIZE;
	}
	else if(strcmp(argv[1],"--int=3") == 0)
	{
		strcat(op_name,"int3.xsm");
		addrBaseVal = T_INTERRUPT + 3*PAGE_PER_INTERRUPT*PAGE_SIZE;
	}
	else if(strcmp(argv[1],"--int=4") == 0)
	{
		strcat(op_name,"int4.xsm");
		addrBaseVal = T_INTERRUPT + 4*PAGE_PER_INTERRUPT*PAGE_SIZE;
	}
	else if(strcmp(argv[1],"--int=5") == 0)
	{
		strcat(op_name,"int5.xsm");
		addrBaseVal = T_INTERRUPT + 5*PAGE_PER_INTERRUPT*PAGE_SIZE;
	}
	else if(strcmp(argv[1],"--int=6") == 0)
	{
		strcat(op_name,"int6.xsm");
		addrBaseVal = T_INTERRUPT + 6*PAGE_PER_INTERRUPT*PAGE_SIZE;
	}
	else if(strcmp(argv[1],"--int=7") == 0)
	{
		strcat(op_name,"int7.xsm");
		addrBaseVal = T_INTERRUPT + 7*PAGE_PER_INTERRUPT*PAGE_SIZE;
	}
	else
	{
		printf("Invalid arguement %s\n", argv[1]);
		fclose(input_fp);
		exit(0);
	}
	fp=fopen(".temp","w");
	out_linecount++;
	fprintf(fp,"START\n");
	yyparse();
	fclose(input_fp);
	fclose(fp);
	input_fp = fopen(".temp","r");
	if(!input_fp)
	{
		printf("Writing compiled code to file failed\n");
		return 0;
	}
	fp = fopen(op_name,"w");
	if(!fp)
	{
		fclose(input_fp);
		printf("Writing compiled code to file failed\n");
		return 0;
	}
	while( ( ch = fgetc(input_fp) ) != EOF )
		fputc(ch, fp);
	fclose(input_fp);
	fclose(fp);	
	return 0;
}
int yyerror (char *msg) 
{
	return fprintf (stderr, "%d: %s\n",linecount,msg);
}
